/*
 * FastAPI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Check Faces
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>FaceDetectionModel</returns>
        FaceDetectionModel CheckFacesFaceDetectionPost(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);

        /// <summary>
        /// Check Faces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of FaceDetectionModel</returns>
        ApiResponse<FaceDetectionModel> CheckFacesFaceDetectionPostWithHttpInfo(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);
        /// <summary>
        /// Validate Models
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;DeepFaceVerificationModel&gt;</returns>
        List<DeepFaceVerificationModel> ValidateModelsModelValidationPost(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);

        /// <summary>
        /// Validate Models
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;DeepFaceVerificationModel&gt;</returns>
        ApiResponse<List<DeepFaceVerificationModel>> ValidateModelsModelValidationPostWithHttpInfo(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);
        /// <summary>
        /// Verify By Lmm
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LLMResultModel</returns>
        LLMResultModel VerifyByLmmCheckByLLMPost(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);

        /// <summary>
        /// Verify By Lmm
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LLMResultModel</returns>
        ApiResponse<LLMResultModel> VerifyByLmmCheckByLLMPostWithHttpInfo(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Check Faces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FaceDetectionModel</returns>
        System.Threading.Tasks.Task<FaceDetectionModel> CheckFacesFaceDetectionPostAsync(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Check Faces
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FaceDetectionModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<FaceDetectionModel>> CheckFacesFaceDetectionPostWithHttpInfoAsync(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Validate Models
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DeepFaceVerificationModel&gt;</returns>
        System.Threading.Tasks.Task<List<DeepFaceVerificationModel>> ValidateModelsModelValidationPostAsync(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Validate Models
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DeepFaceVerificationModel&gt;)</returns>
        System.Threading.Tasks.Task<ApiResponse<List<DeepFaceVerificationModel>>> ValidateModelsModelValidationPostWithHttpInfoAsync(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        /// <summary>
        /// Verify By Lmm
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LLMResultModel</returns>
        System.Threading.Tasks.Task<LLMResultModel> VerifyByLmmCheckByLLMPostAsync(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Verify By Lmm
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LLMResultModel)</returns>
        System.Threading.Tasks.Task<ApiResponse<LLMResultModel>> VerifyByLmmCheckByLLMPostWithHttpInfoAsync(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IDefaultApi : IDefaultApiSync, IDefaultApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class DefaultApi : IDefaultApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class.
        /// </summary>
        /// <returns></returns>
        public DefaultApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public DefaultApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DefaultApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public DefaultApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Check Faces 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>FaceDetectionModel</returns>
        public FaceDetectionModel CheckFacesFaceDetectionPost(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<FaceDetectionModel> localVarResponse = CheckFacesFaceDetectionPostWithHttpInfo(file1, file2);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Check Faces 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of FaceDetectionModel</returns>
        public Org.OpenAPITools.Client.ApiResponse<FaceDetectionModel> CheckFacesFaceDetectionPostWithHttpInfo(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->CheckFacesFaceDetectionPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->CheckFacesFaceDetectionPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.CheckFacesFaceDetectionPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<FaceDetectionModel>("/faceDetection/", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CheckFacesFaceDetectionPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Check Faces 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of FaceDetectionModel</returns>
        public async System.Threading.Tasks.Task<FaceDetectionModel> CheckFacesFaceDetectionPostAsync(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<FaceDetectionModel> localVarResponse = await CheckFacesFaceDetectionPostWithHttpInfoAsync(file1, file2, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Check Faces 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (FaceDetectionModel)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<FaceDetectionModel>> CheckFacesFaceDetectionPostWithHttpInfoAsync(System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->CheckFacesFaceDetectionPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->CheckFacesFaceDetectionPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.CheckFacesFaceDetectionPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<FaceDetectionModel>("/faceDetection/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CheckFacesFaceDetectionPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Validate Models 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>List&lt;DeepFaceVerificationModel&gt;</returns>
        public List<DeepFaceVerificationModel> ValidateModelsModelValidationPost(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<List<DeepFaceVerificationModel>> localVarResponse = ValidateModelsModelValidationPostWithHttpInfo(detectorBackend, file1, file2);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate Models 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of List&lt;DeepFaceVerificationModel&gt;</returns>
        public Org.OpenAPITools.Client.ApiResponse<List<DeepFaceVerificationModel>> ValidateModelsModelValidationPostWithHttpInfo(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->ValidateModelsModelValidationPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->ValidateModelsModelValidationPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "detectorBackend", detectorBackend));
            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.ValidateModelsModelValidationPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<List<DeepFaceVerificationModel>>("/modelValidation/", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValidateModelsModelValidationPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Validate Models 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of List&lt;DeepFaceVerificationModel&gt;</returns>
        public async System.Threading.Tasks.Task<List<DeepFaceVerificationModel>> ValidateModelsModelValidationPostAsync(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<List<DeepFaceVerificationModel>> localVarResponse = await ValidateModelsModelValidationPostWithHttpInfoAsync(detectorBackend, file1, file2, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate Models 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="detectorBackend"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (List&lt;DeepFaceVerificationModel&gt;)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<List<DeepFaceVerificationModel>>> ValidateModelsModelValidationPostWithHttpInfoAsync(DetectorBackend detectorBackend, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->ValidateModelsModelValidationPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->ValidateModelsModelValidationPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(Org.OpenAPITools.Client.ClientUtils.ParameterToMultiMap("", "detectorBackend", detectorBackend));
            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.ValidateModelsModelValidationPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<List<DeepFaceVerificationModel>>("/modelValidation/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValidateModelsModelValidationPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify By Lmm 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>LLMResultModel</returns>
        public LLMResultModel VerifyByLmmCheckByLLMPost(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<LLMResultModel> localVarResponse = VerifyByLmmCheckByLLMPostWithHttpInfo(faceDetectionModel, file1, file2);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify By Lmm 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of LLMResultModel</returns>
        public Org.OpenAPITools.Client.ApiResponse<LLMResultModel> VerifyByLmmCheckByLLMPostWithHttpInfo(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0)
        {
            // verify the required parameter 'faceDetectionModel' is set
            if (faceDetectionModel == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'faceDetectionModel' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }

            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            var localVarMultipartFormData = localVarContentType == "multipart/form-data";
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FormParameters.Add("faceDetectionModel", Org.OpenAPITools.Client.ClientUtils.ParameterToString(faceDetectionModel)); // form parameter
            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.VerifyByLmmCheckByLLMPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Post<LLMResultModel>("/checkByLLM/", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyByLmmCheckByLLMPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Verify By Lmm 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of LLMResultModel</returns>
        public async System.Threading.Tasks.Task<LLMResultModel> VerifyByLmmCheckByLLMPostAsync(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<LLMResultModel> localVarResponse = await VerifyByLmmCheckByLLMPostWithHttpInfoAsync(faceDetectionModel, file1, file2, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Verify By Lmm 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="faceDetectionModel"></param>
        /// <param name="file1"></param>
        /// <param name="file2"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (LLMResultModel)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<LLMResultModel>> VerifyByLmmCheckByLLMPostWithHttpInfoAsync(string faceDetectionModel, System.IO.Stream file1, System.IO.Stream file2, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'faceDetectionModel' is set
            if (faceDetectionModel == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'faceDetectionModel' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }

            // verify the required parameter 'file1' is set
            if (file1 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file1' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }

            // verify the required parameter 'file2' is set
            if (file2 == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'file2' when calling DefaultApi->VerifyByLmmCheckByLLMPost");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.FormParameters.Add("faceDetectionModel", Org.OpenAPITools.Client.ClientUtils.ParameterToString(faceDetectionModel)); // form parameter
            localVarRequestOptions.FileParameters.Add("file1", file1);
            localVarRequestOptions.FileParameters.Add("file2", file2);

            localVarRequestOptions.Operation = "DefaultApi.VerifyByLmmCheckByLLMPost";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<LLMResultModel>("/checkByLLM/", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("VerifyByLmmCheckByLLMPost", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
